export default function Head() {
  return (
    <>
      <title>UI Tailwind</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* <script src="https://cdn.tailwindcss.com"></script> */}

      {/* <link href="/dist/output.css" rel="stylesheet" /> */}
    </>
  )
}
